# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
    build:
        docker:
        -   image: circleci/python:3.6.1

        working_directory: ~/django-jwt

        steps:
        - checkout

        -   restore_cache:
                keys:
                - v1-dependencies-{{ checksum "./examples/django20/requirements.txt" }}
                # fallback to using the latest cache if no exact match is found
                - v1-dependencies-

        -   run:
                name: install dependencies
                command: |
                    cd examples/django20/
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt

        -   save_cache:
                paths:
                - ./examples/django20/venv
                key: v1-dependencies-{{ checksum "./examples/django20/requirements.txt" }}

        # run tests!
        # this example uses Django's built-in test-runner
        # other common Python testing frameworks include pytest and nose
        # https://pytest.org
        # https://nose.readthedocs.io
        -   run:
                name: run tests
                command: |
                    cd examples/django20/
                    . venv/bin/activate
                    python manage.py test

        -   store_artifacts:
                path: test-reports
                destination: test-reports
